import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from '@/components/common/theme-provider';
import './globals.css';

const sfPro = localFont({
  src: [
    {
      path: './fonts/sfproLight.woff',
      weight: '300',
    },
    {
      path: './fonts/sfproRegular.woff',
      weight: '400',
    },
    {
      path: './fonts/sfproMedium.woff',
      weight: '500',
    },
    {
      path: './fonts/sfproSemibold.woff',
      weight: '600',
    },
    {
      path: './fonts/sfproBold.woff',
      weight: '700',
    },
    {
      path: './fonts/sfproHeavy.woff',
      weight: '800',
    },
  ],
  variable: '--font-sf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
