import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from '@/components/common/theme-provider';

import './globals.css';

const sfPro = localFont({
  src: [
    {
      path: './fonts/sfproLight.woff',
      weight: '300',
    },
    {
      path: './fonts/sfproRegular.woff',
      weight: '400',
    },
    {
      path: './fonts/sfproMedium.woff',
      weight: '500',
    },
    {
      path: './fonts/sfproSemibold.woff',
      weight: '600',
    },
    {
      path: './fonts/sfproBold.woff',
      weight: '700',
    },
    {
      path: './fonts/sfproHeavy.woff',
      weight: '800',
    },
  ],
  variable: '--font-sf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="relative">
      <body className={`${sfPro.variable} antialiased`}>
        <div className="pointer-events-none absolute top-0 z-[4] h-full w-full bg-[url('https://framerusercontent.com/images/rR6HYXBrMmX4cRpXfXUOvpvpB0.png')] bg-noise bg-repeat opacity-[0.08]"></div>
        <div className="m-4 min-h-[calc(100vh_-_32px)] w-[calc(100%_-_32px)] rounded-[40px] border-[2px] border-color-stroke p-3 md-max:m-2 md-max:w-[calc(100%_-_16px)] md-max:p-2">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
